//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRole
    {
        public AspNetRole()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
            this.AspNetUsers2 = new HashSet<AspNetUser>();
            this.AspNetUsers3 = new HashSet<AspNetUser>();
            this.AspNetUsers4 = new HashSet<AspNetUser>();
            this.AspNetUsers5 = new HashSet<AspNetUser>();
            this.AspNetUsers6 = new HashSet<AspNetUser>();
            this.AspNetUsers7 = new HashSet<AspNetUser>();
            this.AspNetUsers8 = new HashSet<AspNetUser>();
            this.AspNetUsers9 = new HashSet<AspNetUser>();
            this.AspNetUsers10 = new HashSet<AspNetUser>();
            this.AspNetUsers11 = new HashSet<AspNetUser>();
            this.AspNetUsers12 = new HashSet<AspNetUser>();
            this.AspNetUsers13 = new HashSet<AspNetUser>();
            this.AspNetUsers14 = new HashSet<AspNetUser>();
            this.AspNetUsers15 = new HashSet<AspNetUser>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers2 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers3 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers4 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers5 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers6 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers7 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers8 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers9 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers10 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers11 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers12 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers13 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers14 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers15 { get; set; }
    }
}
