//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Projects = new HashSet<Project>();
            this.Homework = new HashSet<Homework>();
            this.Exams = new HashSet<Exam>();
        }
    
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string Days { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Professor { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Homework> Homework { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
