//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public int Id { get; set; }
        public string HomeworkName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int CourseId { get; set; }
    
        public virtual Cours Cour { get; set; }
    }
}
